
/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 2.0.3
    2026 03 27 19:10:23
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
(* ORIG_MODULE_NAME="SEG7_inst", LATTICE_IP_GENERATED="1" *) module SEG7_inst (PCLK, 
        RST_N, 
        PADDR, 
        PSEL, 
        PENABLE, 
        PWRITE, 
        PWDATA, 
        PRDATA, 
        PREADY, 
        PSLVERR, 
        SEG7_OUT) ;
    input PCLK ; 
    input RST_N ; 
    input [3:0] PADDR ; 
    input PSEL ; 
    input PENABLE ; 
    input PWRITE ; 
    input [31:0] PWDATA ; 
    output [31:0] PRDATA ; 
    output PREADY ; 
    output PSLVERR ; 
    output [7:0] SEG7_OUT ; 
    SEG7_inst_ipgen_apb_slave apb_slave_inst (.PCLK(PCLK), 
                .RST_N(RST_N), 
                .PADDR(PADDR[3:0]), 
                .PSEL(PSEL), 
                .PENABLE(PENABLE), 
                .PWRITE(PWRITE), 
                .PWDATA(PWDATA[31:0]), 
                .PRDATA(PRDATA[31:0]), 
                .PREADY(PREADY), 
                .PSLVERR(PSLVERR), 
                .SEG7_OUT(SEG7_OUT[7:0])) ; 
endmodule



//
//
// Hex to 7Seg decoder wrapped for APB interface
//
// Jay Vos - 2026
//
// Read : Reg0 : ID, Reg1: Hex input, Reg2 : Seg7 output
//
// Write: Reg1 : Hex input
//
module SEG7_inst_ipgen_apb_slave (
    input wire PCLK,  // Clock
    input wire RST_N,  // Active low reset
    input wire [3:0] PADDR,  // Address bus : 3 lower bits, covering 2 full 32bit memory locations 4'h0 and 4'h4
    input wire PSEL,  // Peripheral select
    input wire PENABLE,  // Enable signal
    input wire PWRITE,  // Write/Read control
    input wire [31:0] PWDATA,  // Write data bus
    output reg [31:0] PRDATA,  // Read data bus
    output reg PREADY,  // Peripheral ready
    output reg PSLVERR,  // Error messaging
    output wire [7:0] SEG7_OUT // 7 segment data	
        ) ;
    SEG7_inst_ipgen_hex_to_7seg my_decoder (.clk(PCLK), 
                .reset_n(RST_N), 
                .hex_val(control_reg[7:0]), 
                .seg(SEG7_OUT[7:0])) ; 
    // State Encoding
    localparam IDLE = 2'b00 ; 
    localparam SETUP = 2'b01 ; 
    localparam ACCESS = 2'b10 ; 
    reg [1:0] current_state, 
        next_state ; 
    // Internal Memory-Mapped Register (Example)
    reg [31:0] control_reg ; 
    // 1. State Transition Logic
    always
        @(posedge PCLK or 
            negedge RST_N)
        begin
            if ((!RST_N)) 
                current_state <=  IDLE ;
            else
                current_state <=  next_state ;
        end
    // 2. Next State Logic
    always
        @(*)
        begin
            case (current_state)
            IDLE : 
                begin
                    if (PSEL) 
                        next_state = SETUP ;
                    else
                        next_state = IDLE ;
                end
            SETUP : 
                begin
                    next_state = ACCESS ;
                end
            ACCESS : 
                begin
                    if (PREADY) 
                        next_state = IDLE ;
                    else
                        next_state = ACCESS ;
                end
            default : 
                next_state = IDLE ;
            endcase 
        end
    // 3. APB Output and Register Logic
    always
        @(posedge PCLK or 
            negedge RST_N)
        begin
            if ((!RST_N)) 
                begin
                    PSLVERR <=  1'b0 ;
                    PREADY <=  1'b0 ;
                    PRDATA <=  32'h0 ;
                    control_reg <=  32'h0 ;
                end
            else
                begin
                    case (current_state)
                    SETUP : 
                        begin
                            PREADY <=  1'b0 ;// Preparing for access
                        end
                    ACCESS : 
                        begin
                            PREADY <=  1'b1 ;// In this simple example, we are always ready
                            if (PWRITE) 
                                begin
                                    // Write Operation
                                    // Ignore unknown addresses
                                    case (PADDR)
                                    4'h4 : 
                                        begin
                                            // only 32 bit adress 1 (0x04) can be written
                                            control_reg <=  PWDATA ;// bit7:0 is the hex input for the Seg7 converter
                                        end
                                    default : 
                                        ; 
                                    endcase 
                                end
                            else
                                begin
                                    // Read Operation
                                    case (PADDR)
                                    4'h0 : 
                                        begin
                                            PRDATA <=  32'hDEADBEEF ;// adress 0 = ID
                                        end
                                    4'h4 : 
                                        begin
                                            PRDATA <=  control_reg ;// adress 1 = Hex input data
                                        end
                                    4'h8 : 
                                        begin
                                            PRDATA <=  {24'h0,
                                                    SEG7_OUT[7:0]} ;// adress 2 = 7Seg output data
                                        end
                                    default : 
                                        PRDATA <=  32'hDEADBEEF ;
                                    endcase 
                                end
                        end
                    default : 
                        begin
                            PREADY <=  1'b0 ;
                        end
                    endcase 
                end
        end
endmodule



//
//
// Hex to 7Seg decoder
//
// Jay Vos - 2026
//
//
//
//
//
module SEG7_inst_ipgen_hex_to_7seg (
    input clk, 
    input reset_n,  // _n suffix is standard notation for Active Low
    input [7:0] hex_val, 
    output reg [7:0] seg // dp g f e d c b a
        ) ;
    // Trigger on the Falling Edge of the reset signal
    always
        @(posedge clk or 
            negedge reset_n)
        begin
            if ((!reset_n)) 
                begin
                    seg[6:0] <=  7'b1111111 ;// All segments OFF (Active Low)
                    seg[7] <=  1'b1 ;
                end
            else
                begin
                    case (hex_val[6:0])
                    7'h00 : 
                        // Patterns are bitwise inverted (~): 0 is ON, 1 is OFF
                        seg[6:0] <=  7'b1000000 ;
                    7'h01 : 
                        // 0
                        seg[6:0] <=  7'b1111001 ;
                    7'h02 : 
                        // 1
                        seg[6:0] <=  7'b0100100 ;
                    7'h03 : 
                        // 2
                        seg[6:0] <=  7'b0110000 ;
                    7'h04 : 
                        // 3
                        seg[6:0] <=  7'b0011001 ;
                    7'h05 : 
                        // 4
                        seg[6:0] <=  7'b0010010 ;
                    7'h06 : 
                        // 5
                        seg[6:0] <=  7'b0000010 ;
                    7'h07 : 
                        // 6
                        seg[6:0] <=  7'b1111000 ;
                    7'h08 : 
                        // 7
                        seg[6:0] <=  7'b0000000 ;
                    7'h09 : 
                        // 8
                        seg[6:0] <=  7'b0010000 ;
                    7'h0A : 
                        // 9
                        seg[6:0] <=  7'b0001000 ;
                    7'h0B : 
                        // A
                        seg[6:0] <=  7'b0000011 ;
                    7'h0C : 
                        // b
                        seg[6:0] <=  7'b1000110 ;
                    7'h0D : 
                        // C
                        seg[6:0] <=  7'b0100001 ;
                    7'h0E : 
                        // d
                        seg[6:0] <=  7'b0000110 ;
                    7'h0F : 
                        // E
                        seg[6:0] <=  7'b0001110 ;
                    7'h10 : 
                        // F
                        seg[6:0] <=  7'b0001001 ;
                    7'h11 : 
                        // X
                        seg[6:0] <=  7'b1000000 ;
                    7'h12 : 
                        // O
                        seg[6:0] <=  7'b0011001 ;
                    7'h13 : 
                        // 4
                        seg[6:0] <=  7'b1111110 ;
                    7'h14 : 
                        // round1 a
                        seg[6:0] <=  7'b1111101 ;
                    7'h15 : 
                        // round1 b
                        seg[6:0] <=  7'b1111011 ;
                    7'h16 : 
                        // round1 c
                        seg[6:0] <=  7'b1110111 ;
                    7'h17 : 
                        // round1 d
                        seg[6:0] <=  7'b1101111 ;
                    7'h18 : 
                        // round1 e
                        seg[6:0] <=  7'b1011111 ;
                    7'h19 : 
                        // round1 f
                        seg[6:0] <=  7'b0111111 ;
                    7'h20 : 
                        // round1 g				
                        seg[6:0] <=  7'b1001001 ;
                    7'h21 : 
                        // special ||		
                        seg[6:0] <=  7'b1110110 ;
                    7'h22 : 
                        // special =		
                        seg[6:0] <=  7'b1110110 ;
                    7'h23 : 
                        // special #
                        seg[6:0] <=  7'b0011100 ;
                    7'h24 : 
                        // special hig o
                        seg[6:0] <=  7'b0100011 ;
                    default : 
                        // special low o
                        seg[6:0] <=  7'b1111111 ;
                    endcase 
                    case (hex_val[7])
                    1'b0 : 
                        // Bit 8 is DP segment inverted output				
                        seg[7] <=  1'b1 ;
                    1'b1 : 
                        seg[7] <=  1'b0 ;
                    endcase 
                end
        end
endmodule


