/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 2.0.3
    2026 03 27 19:10:23
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module SEG7_inst (PCLK, RST_N, PADDR, PSEL, PENABLE, PWRITE, PWDATA, PRDATA,
    PREADY, PSLVERR, SEG7_OUT)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  PCLK;
    input  RST_N;
    input  [3:0]  PADDR;
    input  PSEL;
    input  PENABLE;
    input  PWRITE;
    input  [31:0]  PWDATA;
    output  [31:0]  PRDATA;
    output  PREADY;
    output  PSLVERR;
    output  [7:0]  SEG7_OUT;
endmodule