/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 3.0.5
    2026 03 27 19:26:51
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module SPI_4WIRE_inst (clk_i, rst_n_i, sclk_i, PSEL, PENABLE, PADDR, PWRITE,
    PWDATA, PRDATA, PREADY, PSLVERR, SCLK, DC, CS, SDIN, RST)/* synthesis ORIG_MODULE_NAME="SPI_4WIRE_inst" */ /* synthesis LATTICE_IP_GENERATED="1" */;
    input  clk_i;
    input  rst_n_i;
    input  sclk_i;
    input  PSEL;
    input  PENABLE;
    input  [7:0]  PADDR;
    input  PWRITE;
    input  [31:0]  PWDATA;
    output  [31:0]  PRDATA;
    output  PREADY;
    output  PSLVERR;
    output  SCLK;
    output  DC;
    output  CS;
    output  SDIN;
    output  RST;
    apb_to_spi apb_to_spi_inst(.clk_i(clk_i),
        .rst_n_i(rst_n_i),
        .sclk_i(sclk_i),
        .PSEL(PSEL),
        .PENABLE(PENABLE),
        .PADDR(PADDR[7:0]),
        .PWRITE(PWRITE),
        .PWDATA(PWDATA[31:0]),
        .PRDATA(PRDATA[31:0]),
        .PREADY(PREADY),
        .PSLVERR(PSLVERR),
        .SCLK(SCLK),
        .DC(DC),
        .CS(CS),
        .SDIN(SDIN),
        .RST(RST));
endmodule