/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 3.0.5
    2026 03 27 19:26:51
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module SPI_4WIRE_inst (clk_i, rst_n_i, sclk_i, PSEL, PENABLE, PADDR, PWRITE,
    PWDATA, PRDATA, PREADY, PSLVERR, SCLK, DC, CS, SDIN, RST)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  rst_n_i;
    input  sclk_i;
    input  PSEL;
    input  PENABLE;
    input  [7:0]  PADDR;
    input  PWRITE;
    input  [31:0]  PWDATA;
    output  [31:0]  PRDATA;
    output  PREADY;
    output  PSLVERR;
    output  SCLK;
    output  DC;
    output  CS;
    output  SDIN;
    output  RST;
endmodule