/*******************************************************************************
    Verilog netlist generated by IPGEN Lattice Propel (64-bit)
    2025.2.0.2512111315
    Soft IP Version: 2.0.1
    2026 03 14 15:52:59
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module LED_PWM8_inst (pclk, presetn, paddr, psel, penable, pwrite, pwdata,
    prdata, pready, pslverr, led_out)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  pclk;
    input  presetn;
    input  [31:0]  paddr;
    input  psel;
    input  penable;
    input  pwrite;
    input  [31:0]  pwdata;
    output  [31:0]  prdata;
    output  pready;
    output  pslverr;
    output  [7:0]  led_out;
endmodule